In [19]:
import torch
import torch.nn as nn

In [35]:
torch.manual_seed(42)
inputs=torch.tensor([1.0,2.0,3.0])

In [37]:
neuron=nn.Linear(in_features=3,out_features=1)

In [39]:
output=neuron(inputs)

In [41]:
output

tensor([-0.3977], grad_fn=<ViewBackward0>)

In [43]:
#verify

neuron.bias


Parameter containing:
tensor([0.3391], requires_grad=True)

In [45]:
neuron.weight

Parameter containing:
tensor([[-0.1265,  0.1165, -0.2811]], requires_grad=True)

In [47]:
neuron.weight @inputs + neuron.bias

tensor([-0.3977], grad_fn=<AddBackward0>)