In [2]:
import numpy as np
import time

In [6]:
arr=np.array([2,4,6,7,3,5,2])
print(arr)
print(type(arr))

[2 4 6 7 3 5 2]
<class 'numpy.ndarray'>


In [3]:
size=1_00_000
py_list=list(range(size))
start=time.time()
sq_list=[i**2 for i in py_list]
end=time.time()
print(f"python list time is :{end-start}")



np_arr=np.array(py_list)
start=time.time()
sq_arr=np_arr**2
end=time.time()
print(f"python numpy time is :{end-start}")


python list time is :0.016169309616088867
python numpy time is :0.0006129741668701172


In [5]:
#memory
import sys
print(f"python lists size={sys.getsizeof(py_list)*len(py_list)} bytes")

print(f"numpy array size={np_arr.nbytes} bytes")

python lists size=80005600000 bytes
numpy array size=800000 bytes


In [13]:
#create numpy arrays and data types
arr=np.array([34.5,3,2,56,7,34,"hello"])
print(arr,arr.dtype,arr.shape)

arr1=np.array([[34,6,2,5],[25,7,3,78],[34,6,2,5],[25,7,3,78]])
print(arr1,arr1.dtype,arr1.shape)
#U Means unicode data stored in type string

['34.5' '3' '2' '56' '7' '34' 'hello'] <U32 (7,)
[[34  6  2  5]
 [25  7  3 78]
 [34  6  2  5]
 [25  7  3 78]] int64 (4, 4)


In [30]:
#numpy arrays from scratch
arr=np.zeros((4,2),dtype="int64")#zero matrix
print(arr,arr.dtype,arr.shape)

arr1=np.ones((4,3),dtype="int64")#one matrix
print(arr1,arr1.dtype,arr1.shape)

arr2=np.full((3,3),100,dtype="int64")#full matrix
print(arr2,arr2.dtype,arr2.shape)

arr4=np.eye(4)#identity matrix
print(arr4,arr4.shape)

arr5=np.arange(1,11,2)#range elements
print(arr5,arr5.shape)

arr6=np.linspace(1,200,5)#evenly spaced elements
print(arr6,arr6.shape)




[[0 0]
 [0 0]
 [0 0]
 [0 0]] int64 (4, 2)
[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]] int64 (4, 3)
[[100 100 100]
 [100 100 100]
 [100 100 100]] int64 (3, 3)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]] (4, 4)
[1 3 5 7 9] (5,)
[  1.    50.75 100.5  150.25 200.  ] (5,)


In [33]:
#properties

arr=np.array([1,2,3,4,5,6,7,43])
print(arr.size,arr.shape,arr.dtype,arr.ndim)

float_arr=arr.astype(np.float64)
print(float_arr,float_arr.dtype)


8 (8,) int64 1
[ 1.  2.  3.  4.  5.  6.  7. 43.] float64


In [39]:
#operations on arrays
arr=np.array([[2,4,6],[7,3,5]])
print(arr,arr.shape)

reshaped=arr.reshape((3,2))
print(reshaped,reshaped.shape)

flattened=arr.flatten()
print(flattened)

[[2 4 6]
 [7 3 5]] (2, 3)
[[2 4]
 [6 7]
 [3 5]] (3, 2)
[2 4 6 7 3 5]


In [57]:
#indexing
arr=np.array([[2,4,6],[7,3,5]])
print(arr[1][1])

#fancy indexing
arr1=np.array([2,4,6,7,3,5,2])
idx=[1,3,5]
print(arr1[idx])

#boolean indexing
print(arr1[arr1>3])

#slicing
print(arr1[2:5])
print(arr1[2:])
print(arr1[::3])

3
[4 7 5]
[4 6 7 5]
[6 7 3]
[6 7 3 5 2]
[2 7 2]


In [66]:
#multi dimensional arrays
arr2d=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d)
print(np.sum(arr2d))
sumr=np.sum(arr2d,axis=0)
sumc=np.sum(arr2d,axis=1)
print(sumr)
print(sumc)

print(arr2d[0:2,1:2])

[[1 2 3]
 [4 5 6]
 [7 8 9]]
45
[12 15 18]
[ 6 15 24]
[[2]
 [5]]


In [3]:
arr3d=np.array([[[1,2,3],[4,5,6],[7,8,9]],[[11,12,13],[14,15,16],[17,18,19]]])
print(arr3d,arr3d.shape)
print(arr3d[1,1,0])

[[[ 1  2  3]
  [ 4  5  6]
  [ 7  8  9]]

 [[11 12 13]
  [14 15 16]
  [17 18 19]]] (2, 3, 3)
14


In [5]:
#vectorization

arr=np.array([2,4,6,8,3,2])
print(arr**2)

[ 4 16 36 64  9  4]


In [9]:
#Broadcasting
arr=np.array([2,4,6])
arr2d=np.array([[1,2,3],[4,5,6]])
print(arr+arr2d)


[[ 3  6  9]
 [ 6  9 12]]


In [15]:
#normalization
#we use broadcasting to do normalization

arr=np.array([[1,2],[3,4]])
mean=np.mean(arr)
std_dev=np.std(arr)
print(f"normalized :{(arr-mean)/std_dev}")


normalized :[[-1.34164079 -0.4472136 ]
 [ 0.4472136   1.34164079]]


In [39]:
#mathematical functions
arr=np.array([1,2,3,4,5,6,4,2,4])
#aggregation function
print(np.sum(arr))
print(np.prod(arr))
print(np.min(arr))
print(np.max(arr))
print(np.argmin(arr))
print(np.argmax(arr))
print(np.mean(arr))
print(np.median(arr))
print(np.std(arr))
print(np.var(arr))


#power 
print(np.square(arr))
print(np.sqrt(arr))
print(np.pow(arr,4))


#log
print(np.log(arr))
print(np.log10(arr))
print(np.exp(arr))

#round off
print(np.round(5.7))
print(np.ceil(5.7))
print(np.floor(5.7))
print(np.trunc(5.7))
print(np.unique(arr))
print(np.sort(arr))
print(np.abs(arr))

31
23040
1
6
0
5
3.4444444444444446
4.0
1.4989708403591155
2.2469135802469133
[ 1  4  9 16 25 36 16  4 16]
[1.         1.41421356 1.73205081 2.         2.23606798 2.44948974
 2.         1.41421356 2.        ]
[   1   16   81  256  625 1296  256   16  256]
[0.         0.69314718 1.09861229 1.38629436 1.60943791 1.79175947
 1.38629436 0.69314718 1.38629436]
[0.         0.30103    0.47712125 0.60205999 0.69897    0.77815125
 0.60205999 0.30103    0.60205999]
[  2.71828183   7.3890561   20.08553692  54.59815003 148.4131591
 403.42879349  54.59815003   7.3890561   54.59815003]
6.0
6.0
5.0
5.0
[1 2 3 4 5 6]
[1 2 2 3 4 4 4 5 6]
[1 2 3 4 5 6 4 2 4]
